name: Publish packages (Manual)

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Which registry?'
        required: true
        options:
          - npm
          - crates
          - pypi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm:
    if: inputs.name == 'npm'
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  crates:
    if: inputs.name == 'crates'
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  pypi:
    if: inputs.name == 'pypi'
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
